"""create initial schema"""

revision = 'c5d0fcafa90a'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('google_accounts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('google_email', sa.String(length=320), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_google_accounts_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_accounts')),
    sa.UniqueConstraint('organization_id', 'google_email', name='uq_google_accounts_org_email')
    )
    op.create_index(op.f('ix_google_accounts_organization_id'), 'google_accounts', ['organization_id'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('invitation_email', sa.String(length=320), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_memberships_organization_user')
    )
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('owner_id', 'slug', name='uq_projects_owner_slug')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('google_business_profiles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('google_account_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('google_location_name', sa.String(length=255), nullable=False),
    sa.Column('primary_category', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['google_account_id'], ['google_accounts.id'], name=op.f('fk_google_business_profiles_google_account_id_google_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_google_business_profiles_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_business_profiles')),
    sa.UniqueConstraint('organization_id', 'google_location_name', name='uq_gbp_org_location_name')
    )
    op.create_index(op.f('ix_google_business_profiles_google_account_id'), 'google_business_profiles', ['google_account_id'], unique=False)
    op.create_index(op.f('ix_google_business_profiles_location_id'), 'google_business_profiles', ['location_id'], unique=False)
    op.create_index(op.f('ix_google_business_profiles_organization_id'), 'google_business_profiles', ['organization_id'], unique=False)
    op.create_table('target_locations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('uule', sa.String(length=512), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_target_locations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target_locations')),
    sa.UniqueConstraint('id', 'project_id', name='uq_target_locations_id_project_id'),
    sa.UniqueConstraint('project_id', 'uule', name='uq_target_locations_project_uule')
    )
    op.create_index(op.f('ix_target_locations_project_id'), 'target_locations', ['project_id'], unique=False)
    op.create_table('keywords',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('target_location_id', sa.UUID(), nullable=False),
    sa.Column('phrase', sa.String(length=255), nullable=False),
    sa.Column('tracking_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_keywords_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_location_id', 'project_id'], ['target_locations.id', 'target_locations.project_id'], name='fk_keywords_target_location_project_scope', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords')),
    sa.UniqueConstraint('project_id', 'target_location_id', 'phrase', name='uq_keywords_project_location_phrase')
    )
    op.create_index(op.f('ix_keywords_project_id'), 'keywords', ['project_id'], unique=False)
    op.create_index(op.f('ix_keywords_target_location_id'), 'keywords', ['target_location_id'], unique=False)
    op.create_table('heatmap_runs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('target_location_id', sa.UUID(), nullable=False),
    sa.Column('keyword_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('grid_size', sa.Integer(), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('grid_points_total', sa.Integer(), nullable=False),
    sa.Column('center_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('center_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_heatmap_runs_keyword_id_keywords'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_heatmap_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_location_id'], ['target_locations.id'], name=op.f('fk_heatmap_runs_target_location_id_target_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heatmap_runs'))
    )
    op.create_index(op.f('ix_heatmap_runs_keyword_id'), 'heatmap_runs', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_heatmap_runs_project_id'), 'heatmap_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_heatmap_runs_target_location_id'), 'heatmap_runs', ['target_location_id'], unique=False)
    op.create_table('ranking_history',
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('target_location_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('query_keyword', sa.String(length=255), nullable=False),
    sa.Column('location_label', sa.String(length=255), nullable=False),
    sa.Column('uule', sa.String(length=512), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('organic_rank', sa.Integer(), nullable=True),
    sa.Column('map_pack_rank', sa.Integer(), nullable=True),
    sa.Column('organic_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('map_pack_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_ranking_history_keyword_id_keywords'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ranking_history_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_location_id'], ['target_locations.id'], name=op.f('fk_ranking_history_target_location_id_target_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranking_history'))
    )
    op.create_index(op.f('ix_ranking_history_keyword_id'), 'ranking_history', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_ranking_history_project_id'), 'ranking_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_ranking_history_target_location_id'), 'ranking_history', ['target_location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranking_history_target_location_id'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_project_id'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_keyword_id'), table_name='ranking_history')
    op.drop_table('ranking_history')
    op.drop_index(op.f('ix_heatmap_runs_target_location_id'), table_name='heatmap_runs')
    op.drop_index(op.f('ix_heatmap_runs_project_id'), table_name='heatmap_runs')
    op.drop_index(op.f('ix_heatmap_runs_keyword_id'), table_name='heatmap_runs')
    op.drop_table('heatmap_runs')
    op.drop_index(op.f('ix_keywords_target_location_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_project_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_target_locations_project_id'), table_name='target_locations')
    op.drop_table('target_locations')
    op.drop_index(op.f('ix_google_business_profiles_organization_id'), table_name='google_business_profiles')
    op.drop_index(op.f('ix_google_business_profiles_location_id'), table_name='google_business_profiles')
    op.drop_index(op.f('ix_google_business_profiles_google_account_id'), table_name='google_business_profiles')
    op.drop_table('google_business_profiles')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_google_accounts_organization_id'), table_name='google_accounts')
    op.drop_table('google_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
